create table if not exists premier.forum_subforums (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]{3,40}$'),
  name text not null check (char_length(trim(name)) between 2 and 80),
  description text null,
  is_active boolean not null default true,
  created_by integer null references premier.usuario(id_usuario) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists premier.forum_posts (
  id bigint generated by default as identity primary key,
  subforum_id bigint not null references premier.forum_subforums(id) on delete restrict,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  title text not null check (char_length(trim(title)) between 4 and 160),
  body text not null check (char_length(trim(body)) between 1 and 10000),
  image_path text null,
  image_width integer null check (image_width is null or image_width > 0),
  image_height integer null check (image_height is null or image_height > 0),
  status text not null default 'published' check (status in ('published', 'pending_review', 'rejected', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz null
);

create table if not exists premier.forum_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references premier.forum_posts(id) on delete cascade,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  status text not null default 'published' check (status in ('published', 'pending_review', 'rejected', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz null
);

create table if not exists premier.forum_post_votes (
  post_id bigint not null references premier.forum_posts(id) on delete cascade,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (post_id, id_usuario)
);

create table if not exists premier.forum_comment_votes (
  comment_id bigint not null references premier.forum_comments(id) on delete cascade,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (comment_id, id_usuario)
);

create table if not exists premier.forum_reports (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('post', 'comment')),
  target_id bigint not null,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  reason text not null check (char_length(trim(reason)) between 3 and 800),
  status text not null default 'open' check (status in ('open', 'reviewed', 'dismissed', 'resolved')),
  created_at timestamptz not null default now(),
  reviewed_by integer null references premier.usuario(id_usuario) on delete set null,
  reviewed_at timestamptz null
);

create table if not exists premier.moderation_events (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('post', 'comment', 'live_chat')),
  target_id bigint not null,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  scope text not null default 'forum' check (scope in ('forum', 'live_chat', 'app')),
  provider text not null default 'openai',
  model text not null,
  status text not null check (status in ('clean', 'flagged', 'error')),
  action text not null check (action in ('published', 'pending_review', 'blocked')),
  categories jsonb not null default '{}'::jsonb,
  category_scores jsonb not null default '{}'::jsonb,
  raw_response jsonb null,
  created_at timestamptz not null default now()
);

create table if not exists premier.moderation_actions (
  id bigint generated by default as identity primary key,
  event_id bigint null references premier.moderation_events(id) on delete set null,
  admin_id integer not null references premier.usuario(id_usuario) on delete cascade,
  action text not null check (action in ('approve', 'reject', 'ban_user', 'unban_user', 'resolve_report')),
  notes text null,
  created_at timestamptz not null default now()
);

create table if not exists premier.user_restrictions (
  id bigint generated by default as identity primary key,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  scope text not null check (scope in ('forum', 'live_chat', 'app')),
  restriction_type text not null default 'read_only' check (restriction_type in ('read_only', 'blocked')),
  reason text null,
  active boolean not null default true,
  created_by integer null references premier.usuario(id_usuario) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz null,
  lifted_by integer null references premier.usuario(id_usuario) on delete set null,
  lifted_at timestamptz null
);

create index if not exists forum_posts_subforum_status_created_idx
  on premier.forum_posts (subforum_id, status, published_at desc);

create index if not exists forum_comments_post_status_created_idx
  on premier.forum_comments (post_id, status, created_at asc);

create index if not exists forum_reports_status_created_idx
  on premier.forum_reports (status, created_at desc);

create index if not exists moderation_events_scope_status_created_idx
  on premier.moderation_events (scope, status, created_at desc);

create unique index if not exists user_restrictions_active_scope_idx
  on premier.user_restrictions (id_usuario, scope)
  where active = true;

insert into premier.forum_subforums (slug, name, description)
values ('tottenham', 'Tottenham', 'Discusion para fans de Tottenham Hotspur.')
on conflict (slug) do nothing;

insert into storage.buckets (id, name, public)
values ('forum-media', 'forum-media', false)
on conflict (id) do nothing;

alter table premier.forum_subforums enable row level security;
alter table premier.forum_posts enable row level security;
alter table premier.forum_comments enable row level security;
alter table premier.forum_post_votes enable row level security;
alter table premier.forum_comment_votes enable row level security;
alter table premier.forum_reports enable row level security;
alter table premier.moderation_events enable row level security;
alter table premier.moderation_actions enable row level security;
alter table premier.user_restrictions enable row level security;

grant usage on schema premier to service_role;

grant select, insert, update, delete on table
  premier.forum_subforums,
  premier.forum_posts,
  premier.forum_comments,
  premier.forum_post_votes,
  premier.forum_comment_votes,
  premier.forum_reports,
  premier.moderation_events,
  premier.moderation_actions,
  premier.user_restrictions
to service_role;

grant usage, select on all sequences in schema premier to service_role;
