create schema if not exists premier;

create table if not exists premier.live_matches (
  id bigint primary key,
  league text not null default 'Premier League',
  minute text not null default '0''',
  minute_number integer null check (minute_number is null or minute_number >= 0),
  stadium text null,
  status text not null default 'Live',
  home_team_id bigint null,
  home_name text not null,
  home_logo text null,
  home_score integer not null default 0,
  away_team_id bigint null,
  away_name text not null,
  away_logo text null,
  away_score integer not null default 0,
  source text not null default 'api' check (source in ('api', 'manual')),
  is_demo boolean not null default false,
  is_visible boolean not null default false,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table premier.live_matches
  add column if not exists minute_number integer null,
  add column if not exists home_team_id bigint null,
  add column if not exists away_team_id bigint null,
  add column if not exists source text not null default 'api',
  add column if not exists is_demo boolean not null default false,
  add column if not exists is_visible boolean not null default false,
  add column if not exists sort_order integer not null default 0;

create index if not exists live_matches_visible_updated_idx
  on premier.live_matches (is_visible, updated_at desc);

alter table premier.live_matches
  alter column is_visible set default false;

update premier.live_matches
set is_visible = false
where source = 'api'
  and is_demo = false
  and updated_at < now() - interval '2 hours';

create table if not exists premier.live_lineups (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references premier.live_matches(id) on delete cascade,
  team text not null check (team in ('home', 'away')),
  player_number integer null,
  player_name text not null,
  player_position text null,
  player_grid text null,
  is_sub boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table premier.live_lineups
  add column if not exists player_position text null,
  add column if not exists player_grid text null,
  add column if not exists sort_order integer not null default 0;

create index if not exists live_lineups_fixture_team_idx
  on premier.live_lineups (fixture_id, team, is_sub, sort_order, player_number);

create table if not exists premier.live_stats (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references premier.live_matches(id) on delete cascade,
  label text not null,
  home_value text not null default '0',
  away_value text not null default '0',
  updated_at timestamptz not null default now(),
  unique (fixture_id, label)
);

create table if not exists premier.live_stat_snapshots (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references premier.live_matches(id) on delete cascade,
  minute integer not null check (minute >= 0),
  label text not null,
  home_value text not null default '0',
  away_value text not null default '0',
  unique (fixture_id, minute, label)
);

create index if not exists live_stat_snapshots_fixture_minute_idx
  on premier.live_stat_snapshots (fixture_id, minute);

create table if not exists premier.live_events (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references premier.live_matches(id) on delete cascade,
  event_order integer not null default 0,
  minute integer null,
  extra integer null,
  display_minute text null,
  team text null check (team in ('home', 'away')),
  team_id bigint null,
  team_name text null,
  team_logo text null,
  player text null,
  assist text null,
  type text not null,
  detail text not null default '',
  comments text null,
  source text not null default 'api' check (source in ('api', 'manual')),
  created_at timestamptz not null default now()
);

create index if not exists live_events_fixture_minute_idx
  on premier.live_events (fixture_id, minute, event_order);

create table if not exists premier.live_h2h (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references premier.live_matches(id) on delete cascade,
  related_fixture_id bigint not null,
  match_date timestamptz null,
  league text not null,
  home_team_id bigint null,
  home_name text not null,
  home_logo text null,
  home_goals integer null,
  away_team_id bigint null,
  away_name text not null,
  away_logo text null,
  away_goals integer null,
  unique (fixture_id, related_fixture_id)
);

create index if not exists live_h2h_fixture_date_idx
  on premier.live_h2h (fixture_id, match_date desc);

create table if not exists premier.live_activations (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references premier.live_matches(id) on delete cascade,
  type text not null check (type in ('poll', 'drop')),
  title text not null,
  description text null,
  payload jsonb not null default '{}'::jsonb,
  reward_points integer not null default 0 check (reward_points >= 0),
  starts_at_minute integer not null check (starts_at_minute >= 0),
  expires_at_minute integer not null check (expires_at_minute > starts_at_minute),
  status text not null default 'active' check (status in ('scheduled', 'active', 'resolved', 'expired')),
  created_at timestamptz not null default now()
);

create index if not exists live_activations_fixture_minute_idx
  on premier.live_activations (fixture_id, starts_at_minute, expires_at_minute);

create table if not exists premier.live_activation_claims (
  id bigint generated by default as identity primary key,
  activation_id bigint not null references premier.live_activations(id) on delete cascade,
  fixture_id bigint not null references premier.live_matches(id) on delete cascade,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  selected_option text null,
  is_correct boolean not null default true,
  reward_points integer not null default 0 check (reward_points >= 0),
  claimed_at timestamptz not null default now(),
  unique (activation_id, id_usuario)
);

create index if not exists live_activation_claims_fixture_user_idx
  on premier.live_activation_claims (fixture_id, id_usuario, claimed_at desc);

create table if not exists premier.live_chat_messages (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references premier.live_matches(id) on delete cascade,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  username text not null,
  message text not null check (char_length(trim(message)) between 1 and 280),
  created_at timestamptz not null default now()
);

create index if not exists live_chat_messages_fixture_created_idx
  on premier.live_chat_messages (fixture_id, created_at desc);

create table if not exists premier.live_stat_labels (
  api_label text primary key,
  display_label text not null,
  sort_order integer not null default 0,
  is_enabled boolean not null default true
);

create table if not exists premier.live_chat_emotes (
  token text primary key,
  label text not null,
  src text not null,
  kind text not null default 'emote' check (kind in ('emote', 'sticker')),
  sort_order integer not null default 0,
  is_enabled boolean not null default true
);

create table if not exists premier.live_runtime_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table premier.live_matches enable row level security;
alter table premier.live_lineups enable row level security;
alter table premier.live_stats enable row level security;
alter table premier.live_stat_snapshots enable row level security;
alter table premier.live_events enable row level security;
alter table premier.live_h2h enable row level security;
alter table premier.live_activations enable row level security;
alter table premier.live_activation_claims enable row level security;
alter table premier.live_chat_messages enable row level security;
alter table premier.live_stat_labels enable row level security;
alter table premier.live_chat_emotes enable row level security;
alter table premier.live_runtime_settings enable row level security;

grant usage on schema premier to service_role;

grant select, insert, update, delete on table
  premier.live_matches,
  premier.live_lineups,
  premier.live_stats,
  premier.live_stat_snapshots,
  premier.live_events,
  premier.live_h2h,
  premier.live_activations,
  premier.live_activation_claims,
  premier.live_chat_messages,
  premier.live_stat_labels,
  premier.live_chat_emotes,
  premier.live_runtime_settings
to service_role;

grant usage, select on all sequences in schema premier to service_role;
