create table if not exists premier.live_activations (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null,
  type text not null check (type in ('poll', 'drop')),
  title text not null,
  description text null,
  payload jsonb not null default '{}'::jsonb,
  reward_points integer not null default 0 check (reward_points >= 0),
  starts_at_minute integer not null check (starts_at_minute >= 0),
  expires_at_minute integer not null check (expires_at_minute > starts_at_minute),
  status text not null default 'active' check (status in ('scheduled', 'active', 'resolved', 'expired')),
  created_at timestamptz not null default now()
);

create index if not exists live_activations_fixture_minute_idx
  on premier.live_activations (fixture_id, starts_at_minute, expires_at_minute);

create table if not exists premier.live_activation_claims (
  id bigint generated by default as identity primary key,
  activation_id bigint not null,
  fixture_id bigint not null,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  selected_option text null,
  is_correct boolean not null default true,
  reward_points integer not null default 0 check (reward_points >= 0),
  claimed_at timestamptz not null default now(),
  unique (activation_id, id_usuario)
);

create index if not exists live_activation_claims_fixture_user_idx
  on premier.live_activation_claims (fixture_id, id_usuario, claimed_at desc);

alter table premier.live_activations enable row level security;
alter table premier.live_activation_claims enable row level security;
