create table if not exists premier.live_chat_messages (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null,
  id_usuario integer not null references premier.usuario(id_usuario) on delete cascade,
  username text not null,
  message text not null check (char_length(trim(message)) between 1 and 280),
  created_at timestamptz not null default now()
);

create index if not exists live_chat_messages_fixture_created_idx
  on premier.live_chat_messages (fixture_id, created_at desc);

alter table premier.live_chat_messages enable row level security;
